export const dataset = [
  {
    week: 1,
    projects: [
      {
        title: 'Buttons',
        day: 1,
        thumbnail: 'https://www.youtube.com/watch?v=aGJMBPCqnag&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day1-button',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day1',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=0%3A1',
      },
      {
        title: 'Avatars',
        day: 2,
        thumbnail: 'https://www.youtube.com/watch?v=GpBf6UK28KA&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day2-avatar',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day2',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=9%3A161',
      },
      {
        title: 'Recipe card',
        day: 4,
        thumbnail: 'https://www.youtube.com/watch?v=TlMZVRyhhl0&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day4-recipe',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day4',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=233%3A26',
      },
      {
        title: 'Contact Us',
        day: 5,
        thumbnail: 'https://www.youtube.com/watch?v=IB8H0ytMAFk&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day5-contact-us',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day5',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=269%3A26',
      },
      {
        title: 'News letter',
        day: 5,
        thumbnail: 'https://www.youtube.com/watch?v=6_aSp592pKo&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day5-newsletter',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day5',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=269%3A26',
      },
      {
        title: 'Dark and Light',
        day: 6,
        thumbnail: 'https://www.youtube.com/watch?v=6_aSp592pKo&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day6-headerfooter',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day6',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=367%3A1515',
      },
    ],
  },
  {
    week: 2,
    projects: [
      {
        title: 'pomodoro',
        day: 10,
        thumbnail: 'https://www.youtube.com/watch?v=Z9DTjlBm6mk&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day10-pomodoro',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day10',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=635%3A403',
      },
      {
        title: 'image gallery',
        day: 12,
        thumbnail: 'https://www.youtube.com/watch?v=5bT3SYz9-UE&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day12-image-gallery',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day12',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=859%3A409',
      },

      {
        title: 'Week 2 Project',
        day: 14,
        thumbnail: 'https://www.youtube.com/watch?v=gpWSlLlQChk&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day14-weekend-project',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day14-week2',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=916%3A409',
      },
    ],
  },
  {
    week: 3,
    projects: [
      {
        title: 'Input Separator',
        day: 15,
        thumbnail: 'https://www.youtube.com/watch?v=GqyDLWBtFA0&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],

        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day15-input-separator',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day15',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=996%3A409',
      },
      {
        title: 'Advice generator',
        day: 16,
        thumbnail: 'https://www.youtube.com/watch?v=krIdSHUQVKw&ab_channel=begintocode',
        tags: ['starting out', 'buttons'],
        livelink: 'https://30day-ui-challenge-sirjantamang.netlify.app/day16-advice-generator',
        github: 'https://github.com/sirjandrn25/react_30_day_ui_challenge/tree/main/src/challenges/day16',
        figma: 'https://www.figma.com/file/QE89cpxxaOY3qbKMeIZ09Q/30Day?node-id=1029%3A409',
      },
    ],
  },
  {
    week: 4,
    projects: [],
  },
]
